/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-31 02:04:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bsnm;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bsnmJoinWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("/bsnm/../include/header.jsp", Long.valueOf(1693372368286L));
    _jspx_dependants.put("/bsnm/../include/nav.jsp", Long.valueOf(1692337405365L));
    _jspx_dependants.put("jar:file:/C:/HITRIPver0818/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_HITRIP/WEB-INF/lib/spring-webmvc-5.3.6.jar!/META-INF/spring.tld", Long.valueOf(1618279800000L));
    _jspx_dependants.put("/bsnm/../include/footer.jsp", Long.valueOf(1692778084430L));
    _jspx_dependants.put("jar:file:/C:/HITRIPver0818/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_HITRIP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/HITRIPver0818/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_HITRIP/WEB-INF/lib/org.egovframe.rte.ptl.mvc-4.0.0.jar!/META-INF/taglib.tld", Long.valueOf(1640750708000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1691982005951L));
    _jspx_dependants.put("/WEB-INF/lib/org.egovframe.rte.ptl.mvc-4.0.0.jar", Long.valueOf(1691982015424L));
    _jspx_dependants.put("jar:file:/C:/HITRIPver0818/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_HITRIP/WEB-INF/lib/spring-webmvc-5.3.6.jar!/META-INF/spring-form.tld", Long.valueOf(1618279800000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.6.jar", Long.valueOf(1691982003150L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/main.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>사업자 회원가입 화면</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  /* Custom CSS for the form */\r\n");
      out.write("  #container {\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    max-width: 600px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #wrapper_title {\r\n");
      out.write("    font-size: 1.3em;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .mbskin {\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .tbl_frm01 {\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  th,\r\n");
      out.write("  td {\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border-bottom: 1px solid #ccc;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  th {\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    width: 25%;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  input[type=\"text\"],\r\n");
      out.write("  input[type=\"password\"],\r\n");
      out.write("  input[type=\"date\"]   {\r\n");
      out.write("    width: 95%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("  }\r\n");
      out.write("  input[type=\"radio\"],\r\n");
      out.write("  input[type=\"checkbox\"] {\r\n");
      out.write("  	 padding: 10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .frm_info {\r\n");
      out.write("    color: #666;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #msg_bsnmid,{\r\n");
      out.write("    color: #e8180c;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .btn_confirm {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .btn_submit {\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    background-color: #333;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .btn_cancel {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    border: 1px solid #333;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .btn_cancel:hover {\r\n");
      out.write("    background-color: #333;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	\r\n");
      out.write("$(function(){\r\n");
      out.write("	//사업자 등록 상태 조회\r\n");
      out.write("	$( \"#bsnmno\" ).keyup (function () {\r\n");
      out.write("	  // var charLimit = $(this).attr(\"maxlength\");\r\n");
      out.write("\r\n");
      out.write("	   var bsnmno = $(\"#bsnmno\").val();\r\n");
      out.write("	   if (this.value.length == \"10\") {\r\n");
      out.write("\r\n");
      out.write("	          check = {}\r\n");
      out.write("\r\n");
      out.write("	           new Promise( (succ, fail)=>{\r\n");
      out.write("	               var data = {  \"b_no\": [\"\"+ bsnmno +\"\"] }; // String b_no = \"[1234123456]\";\r\n");
      out.write("\r\n");
      out.write("	               $.ajax({\r\n");
      out.write("		               url: \"https://api.odcloud.kr/api/nts-businessman/v1/status?serviceKey=NGC3J%2F3kwKWZZORfbmneNB50s19CnM7Z3ggMyc55TMoPMLUH1G1Sd8sxXF2IkeElWi4BOMTCiIzjGK8dd6Crdw%3D%3D\",  // serviceKey 값을 xxxxxx에 입력\r\n");
      out.write("		               type: \"POST\",\r\n");
      out.write("		               data: JSON.stringify(data), \r\n");
      out.write("		               \r\n");
      out.write("		               dataType: \"JSON\",\r\n");
      out.write("		               contentType: \"application/json\",\r\n");
      out.write("		               accept: \"application/json\",\r\n");
      out.write("		               success: function(result) {\r\n");
      out.write("	\r\n");
      out.write("		                   check_code = result.data[0].b_stt_cd;\r\n");
      out.write("		                   //check_b_no = result.data[0].b_no;\r\n");
      out.write("		                   succ(result);\r\n");
      out.write("	\r\n");
      out.write("		               },\r\n");
      out.write("		               fail: function(result) {\r\n");
      out.write("		                   fail(error);                                    \r\n");
      out.write("		               }\r\n");
      out.write("		           });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	           }).then((arg) =>{   \r\n");
      out.write("\r\n");
      out.write("	               $.ajax({\r\n");
      out.write("	                   url: \"/bsnmnoCheck.do\",\r\n");
      out.write("	                   type: \"post\",\r\n");
      out.write("	                   data: { \"bsnmno\": bsnmno },\r\n");
      out.write("	                   \r\n");
      out.write("	                   dataType: \"text\",\r\n");
      out.write("	                   success: function(result) {\r\n");
      out.write("\r\n");
      out.write("	                       $(\"#bs_result\").css(\"display\",\"block\");\r\n");
      out.write("\r\n");
      out.write("	                       if (result == \"1\") {\r\n");
      out.write("                               // 기존 등록한 사업자번호와 동일한 경우\r\n");
      out.write("                               $(\"#bs_result\").html(\"<font color='red'>기존에 등록하신 사업자번호와 동일합니다.</font>\");\r\n");
      out.write("                           } else {\r\n");
      out.write("                               // 사업자번호 등록 여부에 따른 처리\r\n");
      out.write("                               if (check_code == \"01\") {\r\n");
      out.write("                                   $(\"#bs_result\").html(\"<font color='green'>정상적인 사업자번호입니다.</font>\");\r\n");
      out.write("                               } else if (check_code == \"02\" || check_code == \"03\") {\r\n");
      out.write("                                   $(\"#bs_result\").html(\"<font color='red'>휴/폐업한 사업자번호입니다.</font>\");\r\n");
      out.write("                               } else {\r\n");
      out.write("                                   $(\"#bs_result\").html(\"<font color='red'>등록되지 않은 사업자번호입니다.</font>\");\r\n");
      out.write("                               }\r\n");
      out.write("                           }\r\n");
      out.write("                       }\r\n");
      out.write("               \r\n");
      out.write("	               });\r\n");
      out.write("\r\n");
      out.write("	           }); //then end\r\n");
      out.write("\r\n");
      out.write("	   }\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$(\"#captcha_reload\").click(function(){\r\n");
      out.write("		\r\n");
      out.write("		var no = $(\"#prevent_no\").val();	//	no값 받아오기\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("	         \r\n");
      out.write("	         type : \"POST\",\r\n");
      out.write("	         url  : \"/bsnmpreventImg.do\",\r\n");
      out.write("	         data : \"no=\"+no,\r\n");
      out.write("\r\n");
      out.write("	         datatype : \"json\",\r\n");
      out.write("	         success  : function(data){\r\n");
      out.write("	            //	data = \"375648,5\"\r\n");
      out.write("	            var datas = data.split(\",\");\r\n");
      out.write("	            var filename = datas[0];\r\n");
      out.write("	            var nn = datas[1];\r\n");
      out.write("	            $(\"#prevent_no\").val(nn);\r\n");
      out.write("				//	attr 속성값을 바꾸는 함수\r\n");
      out.write("				$(\"#filename\").val(filename);\r\n");
      out.write("	            $(\"#captcha_img\").attr(\"src\",\"../images/prevent_img/\"+filename+\".jpg\");\r\n");
      out.write("	         },\r\n");
      out.write("	         error : function(){ }\r\n");
      out.write("	         \r\n");
      out.write("	      });\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("   \r\n");
      out.write("   $(\"#bsnmid\").keyup(function(){\r\n");
      out.write("	  \r\n");
      out.write("	   var bsnmid = $(\"#bsnmid\").val();\r\n");
      out.write("	   var result = 0;\r\n");
      out.write("	   \r\n");
      out.write("	   if (bsnmid.length >= 3 && bsnmid.length <= 20 ) {\r\n");
      out.write("			result = fn_bsnmid(bsnmid);\r\n");
      out.write("	   }\r\n");
      out.write("	   \r\n");
      out.write("	   $(\"#id_usable\").val(\"N\");\r\n");
      out.write("	   if( result == 0 ){\r\n");
      out.write("	         msg = \"<font color = 'red'>아이디는 6자리~20자리 사이로 입력해주세요</font>\";\r\n");
      out.write("       } else if (result == 1 ){\r\n");
      out.write("             msg = \"<font color = 'green'>사용가능한 아이디입니다.</font>\";\r\n");
      out.write("             $(\"#id_usable\").val(\"Y\");\r\n");
      out.write("       } else if(result == 2 ){\r\n");
      out.write("             msg = \"<font color = 'red'>이미사용중인 아이디입니다.</font>\";\r\n");
      out.write("       } else if(result == 3 ){\r\n");
      out.write("             msg = \"<font color = 'red'>형식에 맞지 않는 아이디입니다.</font>\";         \r\n");
      out.write("       }\r\n");
      out.write("      \r\n");
      out.write("       $(\"#msg_bsnmid\").html(msg);\r\n");
      out.write("\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   $(\"#btn_submit\").click(function(){\r\n");
      out.write("	  \r\n");
      out.write("	  let captcha_key = $(\"#captcha_key\").val();\r\n");
      out.write("	  let filename = $(\"#filename\").val();\r\n");
      out.write("	  if( captcha_key != filename ) {\r\n");
      out.write("		  alert(\"자동등록방지 번호를 확인해주세요.\");\r\n");
      out.write("		  $(\"#captcha_key\").focus();\r\n");
      out.write("		  return false;\r\n");
      out.write("	  }\r\n");
      out.write("      \r\n");
      out.write("	  let bsnmid = $.trim($(\"#bsnmid\").val());\r\n");
      out.write("      let bsnmpass = $.trim($(\"#bsnmpass\").val());\r\n");
      out.write("      let pass2 = $.trim($(\"#pass2\").val());\r\n");
      out.write("      let bsnmname = $.trim($(\"#bsnmname\").val());\r\n");
      out.write("      let bsnmphone = $.trim($(\"#bsnmphone\").val());\r\n");
      out.write("      let bsnmmail = $.trim($(\"#bsnmmail\").val());\r\n");
      out.write("      let bsnmno = $.trim($(\"#bsnmno\").val());\r\n");
      out.write("      let bsnmcompany = $.trim($(\"#bsnmcompany\").val());\r\n");
      out.write("      let id_usable = $(\"#id_usable\").val();\r\n");
      out.write("      \r\n");
      out.write("      if( id_usable == \"N\" ) {\r\n");
      out.write("    	  alert(\"아이디를 확인해주세요.\");\r\n");
      out.write("    	  $(\"#bsnmid\").focus();\r\n");
      out.write("    	  return false;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      $(\"#bsnmid\").val(bsnmid);\r\n");
      out.write("      $(\"#bsnmpass\").val(bsnmpass);\r\n");
      out.write("      $(\"#bsnmname\").val(bsnmname);\r\n");
      out.write("      $(\"#bsnmphone\").val(bsnmphone);\r\n");
      out.write("      $(\"#bsnmmail\").val(bsnmmail);\r\n");
      out.write("      $(\"#bsnmno\").val(bsnmno);\r\n");
      out.write("      $(\"#bsnmcompany\").val(bsnmcompany);\r\n");
      out.write("            \r\n");
      out.write("      if ( bsnmid.length < 6 || bsnmid.length > 20 ) {\r\n");
      out.write("         alert(\"아이디는 6~20자 사이로 입력해주세요.\");\r\n");
      out.write("         $(\"#bsnmid\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ( bsnmpass.length < 8 || bsnmpass.length > 20 ) {\r\n");
      out.write("         alert(\"암호는 8~20자 사이로 입력해주세요.\");\r\n");
      out.write("         $(\"#bsnmpass\").focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      if( bsnmpass != pass2 ) {\r\n");
      out.write("    	  alert(\"암호가 일치하지 않습니다.\");\r\n");
      out.write("    	  $(\"#bsnmpass\").focus();\r\n");
      out.write("          return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ( bsnmname == \"\") {\r\n");
      out.write("          alert(\"이름을 입력해주세요.\");\r\n");
      out.write("          $(\"#bsnmname\").focus();\r\n");
      out.write("          return false;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      if (bsnmphone == \"\") {\r\n");
      out.write("          alert(\"핸드폰 번호를 입력해주세요.\");\r\n");
      out.write("          $(\"#bsnmphone\").focus();\r\n");
      out.write("          return false;\r\n");
      out.write("      }\r\n");
      out.write("      if (bsnmmail == \"\") {\r\n");
      out.write("          alert(\"이메일을 입력해주세요.\");\r\n");
      out.write("          $(\"#bsnmmail\").focus();\r\n");
      out.write("          return false;\r\n");
      out.write("      }\r\n");
      out.write("      if (bsnmno == \"\") {\r\n");
      out.write("          alert(\"사업자등록번호를 입력해주세요.\");\r\n");
      out.write("          $(\"#bsnmno\").focus();\r\n");
      out.write("          return false;\r\n");
      out.write("      }\r\n");
      out.write("      if ( bsnmno.length != 10 ) {\r\n");
      out.write("          alert(\"사업자등록번호는 10자리 숫자여야합니다.\");\r\n");
      out.write("          $(\"#bsnmno\").focus();\r\n");
      out.write("          return false;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("  var form = $(\"#frm\").serialize();\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         \r\n");
      out.write("         type : \"POST\",\r\n");
      out.write("         url  : \"/bsnmJoinSave.do\",\r\n");
      out.write("         data : form,\r\n");
      out.write("\r\n");
      out.write("         datatype : \"json\",\r\n");
      out.write("         success  : function(data){\r\n");
      out.write("            if(data == \"1\") {\r\n");
      out.write("               alert(\"저장완료\");\r\n");
      out.write("               location=\"/bsnmLoginWrite.do\";\r\n");
      out.write("            } else if(data == \"2\") {\r\n");
      out.write("            	alert(\"이미 사용중인 아이디입니다.\");\r\n");
      out.write("            } else {\r\n");
      out.write("               alert(\"저장실패!\");\r\n");
      out.write("            }\r\n");
      out.write("         },\r\n");
      out.write("         error : function(){\r\n");
      out.write("            alert(\"전송실패\");\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function fn_bsnmid(bsnmid) {\r\n");
      out.write("	\r\n");
      out.write("	var result = \"\";\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("        \r\n");
      out.write("        type : \"POST\",\r\n");
      out.write("        url  : \"/bsnmIdCheck.do\",\r\n");
      out.write("        async: false,\r\n");
      out.write("        data : \"bsnmid=\"+bsnmid,\r\n");
      out.write("\r\n");
      out.write("        datatype : \"text\",\r\n");
      out.write("        success  : function(data){\r\n");
      out.write("        	result = data;\r\n");
      out.write("        },\r\n");
      out.write("        error : function(){\r\n");
      out.write("        	result = \"2\";\r\n");
      out.write("        }       \r\n");
      out.write("     });\r\n");
      out.write("	return result;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function limitInputLength(inputElement, maxLength) {\r\n");
      out.write("    if (inputElement.value.length > maxLength) {\r\n");
      out.write("        inputElement.value = inputElement.value.slice(0, maxLength);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--header 시작-->\r\n");
      out.write("<header>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function fn_logout() {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			data : \"\",\r\n");
      out.write("			url  : \"/logout.do\",\r\n");
      out.write("			\r\n");
      out.write("			datatype : \"text\",\r\n");
      out.write("			success  : function(data){\r\n");
      out.write("	            if(data == \"1\" ) {\r\n");
      out.write("	               alert(\"로그아웃되었습니다.\");\r\n");
      out.write("	               location=\"/\";\r\n");
      out.write("	            } else {\r\n");
      out.write("	            	alert(\"로그아웃 실패.\");\r\n");
      out.write("	            } \r\n");
      out.write("	         },\r\n");
      out.write("	         error : function(){\r\n");
      out.write("	            alert(\"전송실패\");\r\n");
      out.write("	         }			\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function fn_bsnmlogout() {\r\n");
      out.write("	      \r\n");
      out.write("	      $.ajax({\r\n");
      out.write("	         type : \"POST\",\r\n");
      out.write("	         data : \"\",\r\n");
      out.write("	         url  : \"/bsnmLogout.do\",\r\n");
      out.write("	         \r\n");
      out.write("	         datatype : \"text\",\r\n");
      out.write("	         success  : function(data){\r\n");
      out.write("               if(data == \"1\" ) {\r\n");
      out.write("                  alert(\"로그아웃되었습니다.\");\r\n");
      out.write("                  location=\"/\";\r\n");
      out.write("               } else {\r\n");
      out.write("                  alert(\"로그아웃 실패.\");\r\n");
      out.write("               } \r\n");
      out.write("            },\r\n");
      out.write("            error : function(){\r\n");
      out.write("               alert(\"전송실패\");\r\n");
      out.write("            }         \r\n");
      out.write("	      });\r\n");
      out.write("	   }\r\n");
      out.write("	\r\n");
      out.write("function fn_adminlogout() {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			data : \"\",\r\n");
      out.write("			url  : \"/adminLogout.do\",\r\n");
      out.write("			\r\n");
      out.write("			datatype : \"text\",\r\n");
      out.write("			success  : function(data){\r\n");
      out.write("	            if(data == \"1\" ) {\r\n");
      out.write("	               alert(\"로그아웃되었습니다.\");\r\n");
      out.write("	               location=\"/\";\r\n");
      out.write("	            } else {\r\n");
      out.write("	            	alert(\"로그아웃 실패.\");\r\n");
      out.write("	            } \r\n");
      out.write("	         },\r\n");
      out.write("	         error : function(){\r\n");
      out.write("	            alert(\"전송실패\");\r\n");
      out.write("	         }			\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<ul class=\"header_left\">\r\n");
      out.write("  <li class=\"header_item\">\r\n");
      out.write("  		<a href=\"/\">\r\n");
      out.write("			<img src=\"/tripImage/hitriplogo.png\">\r\n");
      out.write("		</a>\r\n");
      out.write("	</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<ul class=\"header_right\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <li class=\"header_item\">\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"header_item\">\r\n");
      out.write("    <a class=\"header_link\" href=\"/noticeList.do\">공지사항</a>\r\n");
      out.write("  </li>\r\n");
      out.write("  \r\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</ul>");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<!--header 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--nav 시작-->\r\n");
      out.write("<nav>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<div class=\"nav_wrap\">\r\n");
      out.write("		<ul class=\"navbar\">\r\n");
      out.write("		  <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/\">Home </a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		  <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"prtBoardList.do\">동행</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		  <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/planMain.do\">일정</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		 <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/tripList.do\">국내여행지</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		 <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/babList.do\">국내맛집</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		 <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/reviewList.do\">여행후기</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		 <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/packBoardList.do\">패키지여행</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		 <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/packReviewList.do\">패키지여행후기</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<!--nav 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--section 시작-->\r\n");
      out.write("<section>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        \r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("        <div id=\"wrapper_title\">사업자 회원 가입</div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mbskin\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("            <form id=\"frm\" name=\"frm\"> \r\n");
      out.write("            \r\n");
      out.write("            <input type=\"hidden\" id=\"prevent_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" id=\"filename\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${filename }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" id=\"id_usable\" value=\"N\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"tbl_frm01 tbl_wrap\">\r\n");
      out.write("                <table>\r\n");
      out.write("                <caption>사이트 이용정보 입력</caption>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th scope=\"row\"><label for=\"bsnmid\">사업자아이디<strong class=\"sound_only\"></strong></label></th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        \r\n");
      out.write("                        <input type=\"text\" name=\"bsnmid\" value=\"\" id=\"bsnmid\" required=\"\" class=\"frm_input required \" minlength=\"6\" maxlength=\"20\">\r\n");
      out.write("                        <span class=\"frm_info\">영문자, 숫자, _ 만 입력 가능. 최소 3자이상 입력하세요.</span>\r\n");
      out.write("                        <span id=\"msg_bsnmid\"></span>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th scope=\"row\"><label for=\"bsnmpass\">사업자비밀번호<strong class=\"sound_only\"></strong></label></th>\r\n");
      out.write("                    <td><input type=\"password\" name=\"bsnmpass\" id=\"bsnmpass\" required=\"\" class=\"frm_input required\" minlength=\"8\" maxlength=\"20\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th scope=\"row\"><label for=\"pass2\">비밀번호 확인<strong class=\"sound_only\"></strong></label></th>\r\n");
      out.write("                    <td><input type=\"password\" name=\"pass2\" id=\"pass2\" required=\"\" class=\"frm_input required\" minlength=\"8\" maxlength=\"20\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"tbl_frm01 tbl_wrap\">\r\n");
      out.write("                <table>\r\n");
      out.write("                <caption>개인정보 입력</caption>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\"><label for=\"bsnmname\">사업자 이름<strong class=\"sound_only\"></strong></label></th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" id=\"bsnmname\" name=\"bsnmname\" value=\"\" required=\"\" class=\"frm_input required \" size=\"10\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\"><label for=\"bsnmcompany\">사업자 상호<strong class=\"sound_only\"></strong></label></th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" id=\"bsnmcompany\" name=\"bsnmcompany\" value=\"\" required=\"\" class=\"frm_input required \" size=\"10\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\"><label for=\"bsnmphone\">사업자 휴대폰번호<strong class=\"sound_only\"></strong></label></th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" name=\"bsnmphone\" value=\"\" id=\"bsnmphone\" required=\"\" class=\"frm_input required\" maxlength=\"13\" oninput=\"this.value = this.value.replace(/[^-0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\"><label for=\"bsnmmail\">사업자 E-mail<strong class=\"sound_only\"></strong></label></th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" name=\"bsnmmail\" value=\"\" id=\"bsnmmail\" required=\"\" class=\"frm_input email required\" size=\"70\" maxlength=\"100\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\"><label for=\"bsnmrdate\">사업자등록일<strong class=\"sound_only\"></strong></label></th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"date\" name=\"bsnmrdate\" id=\"bsnmrdate\" >\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\"><label for=\"bsnmno\">사업자등록번호<strong class=\"sound_only\"></strong></label></th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"number\" name=\"bsnmno\" id=\"bsnmno\" oninput=\"limitInputLength(this, 10)\">\r\n");
      out.write("                            <span id=\"bs_result\"></span>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"tbl_frm01 tbl_wrap\">\r\n");
      out.write("            <table>\r\n");
      out.write("            <caption>기타 개인설정</caption>\r\n");
      out.write("            <tbody>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("                <th scope=\"row\"><label for=\"bsnmopeninfo\">정보공개</label></th>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"checkbox\" name=\"bsnmopeninfo\" value=\"Y\" id=\"bsnmopeninfo\" checked>\r\n");
      out.write("                    정보를 오픈하겠습니다.\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>            \r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("                <th scope=\"row\">자동등록방지</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <fieldset id=\"captcha\" class=\"captcha\">\r\n");
      out.write("                        <legend><label for=\"captcha_key\">자동등록방지</label></legend>\r\n");
      out.write("                        <div id=\"abc\"><img src=\"../images/prevent_img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${filename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\" alt=\"\" id=\"captcha_img\"></div>\r\n");
      out.write("                        <button type=\"button\" id=\"captcha_reload\"><span></span>새로고침</button><input type=\"text\" name=\"captcha_key\" id=\"captcha_key\" required=\"\" class=\"captcha_box required\" size=\"6\" maxlength=\"6\">\r\n");
      out.write("                        <span id=\"captcha_info\">자동등록방지 숫자를 순서대로 입력하세요.</span>\r\n");
      out.write("                        </fieldset>\r\n");
      out.write("                    </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"btn_confirm\">\r\n");
      out.write("            <input type=\"submit\" value=\"회원가입\" id=\"btn_submit\" onclick=\"return false;\" class=\"btn_submit\" accesskey=\"s\">\r\n");
      out.write("            <a href=\"\" class=\"btn_cancel\">취소</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("<!--section 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--footer 시작-->\r\n");
      out.write("<footer>\r\n");
      out.write("<div class=\"footer1\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<div class=\"footer1\">\r\n");
      out.write("   <ul>\r\n");
      out.write("      <li><a class=\"footer_link\" href=\"/service.do\">이용약관</a></li>\r\n");
      out.write("      <li><a class=\"footer_link\" href=\"/policy.do\">개인정보 처리방침</a></li>\r\n");
      out.write("      <li>메일문의 guri@himedia.co.kr</li>         \r\n");
      out.write("   </ul>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!--footer 끝-->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /bsnm/../include/header.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("s_userid");
      // /bsnm/../include/header.jsp(10,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/bsnm/../include/header.jsp(10,0) '${sessionScope.SessionUserID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionUserID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /bsnm/../include/header.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("s_bsnmid");
      // /bsnm/../include/header.jsp(11,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/bsnm/../include/header.jsp(11,0) '${sessionScope.SessionBsnmID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionBsnmID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /bsnm/../include/header.jsp(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("s_adminid");
      // /bsnm/../include/header.jsp(12,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/bsnm/../include/header.jsp(12,0) '${sessionScope.SessionAdminID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionAdminID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /bsnm/../include/header.jsp(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("s_superid");
      // /bsnm/../include/header.jsp(13,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/bsnm/../include/header.jsp(13,0) '${sessionScope.SessionAdminSuperID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionAdminSuperID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /bsnm/../include/header.jsp(89,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_adminid != null or s_superid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"../adminNoticeList.do\">관리자페이지</a>\r\n");
          out.write("  </li>\r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /bsnm/../include/header.jsp(96,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /bsnm/../include/header.jsp(97,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_bsnmid !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('사');
          out.write('업');
          out.write('자');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_bsnmid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /bsnm/../include/header.jsp(98,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_adminid !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('관');
          out.write('리');
          out.write('자');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_adminid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /bsnm/../include/header.jsp(99,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_superid !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("최고관리자");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_superid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /bsnm/../include/header.jsp(105,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == null and s_bsnmid == null and\r\n  				s_adminid == null and s_superid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"../joinWrite.do\">회원가입</a>\r\n");
          out.write("  </li>\r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"/loginWrite.do\">로그인</a>\r\n");
          out.write("  </li> \r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /bsnm/../include/header.jsp(115,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"../mbrModify.do\">정보수정</a>\r\n");
          out.write("  </li>\r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"javascript:fn_logout()\">로그아웃</a>\r\n");
          out.write("  </li>  \r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /bsnm/../include/header.jsp(125,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_bsnmid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"../bsnmModify.do\">정보수정</a>\r\n");
          out.write("  </li>\r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"javascript:fn_bsnmlogout()\">로그아웃</a>\r\n");
          out.write("  </li>  \r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent(null);
      // /bsnm/../include/header.jsp(134,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_adminid != null or s_superid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"javascript:fn_adminlogout()\">로그아웃</a>\r\n");
          out.write("  </li>  \r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }
}
