/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-31 05:57:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.planboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class planMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("jar:file:/C:/HITRIPver0818/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_HITRIP/WEB-INF/lib/spring-webmvc-5.3.6.jar!/META-INF/spring.tld", Long.valueOf(1618279800000L));
    _jspx_dependants.put("/planboard/../include/nav.jsp", Long.valueOf(1692337405365L));
    _jspx_dependants.put("jar:file:/C:/HITRIPver0818/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_HITRIP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/HITRIPver0818/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_HITRIP/WEB-INF/lib/org.egovframe.rte.ptl.mvc-4.0.0.jar!/META-INF/taglib.tld", Long.valueOf(1640750708000L));
    _jspx_dependants.put("/planboard/../include/header.jsp", Long.valueOf(1693372368286L));
    _jspx_dependants.put("/planboard/../include/footer.jsp", Long.valueOf(1692778084430L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1691982005951L));
    _jspx_dependants.put("/WEB-INF/lib/org.egovframe.rte.ptl.mvc-4.0.0.jar", Long.valueOf(1691982015424L));
    _jspx_dependants.put("jar:file:/C:/HITRIPver0818/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_HITRIP/WEB-INF/lib/spring-webmvc-5.3.6.jar!/META-INF/spring-form.tld", Long.valueOf(1618279800000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.6.jar", Long.valueOf(1691982003150L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/main.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>일정관리</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* section-wrapper 스타일 */\r\n");
      out.write(".section-wrapper {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("}\r\n");
      out.write("h2 {\r\n");
      out.write("  /* Existing styles... */\r\n");
      out.write("  font-size: 5vw; /* Adjust as needed */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#monthYearDisplay {\r\n");
      out.write("  /* Existing styles... */\r\n");
      out.write("  font-size: 4vw; /* Adjust as needed */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("  max-height: 60px; /* Adjust the value as needed */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* section 스타일 */\r\n");
      out.write("section {\r\n");
      out.write("  max-height: calc(90vh - 120px); /* Adjust the value as needed */\r\n");
      out.write("  overflow-y: auto;\r\n");
      out.write("  position: relative; /* Add relative positioning to the section */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("  max-height: 40px; /* Adjust the value as needed */\r\n");
      out.write("}\r\n");
      out.write("/* calendar-container 스타일 */\r\n");
      out.write("#calendar-container {\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("table#calendar {\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 1100px; /* Set the width to 1200px */\r\n");
      out.write("  margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Button container styles */\r\n");
      out.write(".button-container {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  padding: 10px; /* 버튼 컨테이너의 내부 여백 추가 */\r\n");
      out.write("  background-color: #f0f0f0; /* 배경색 추가 */\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-container button {\r\n");
      out.write("  padding: 8px 16px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  background-color: #007bff;\r\n");
      out.write("  color: white;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-container button:hover {\r\n");
      out.write("  background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Calendar table styles */\r\n");
      out.write("h2 {\r\n");
      out.write("  margin: 0 0 15px;\r\n");
      out.write("  font-size: 24px;\r\n");
      out.write("  color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#monthYearDisplay {\r\n");
      out.write("  font-size: 24px;\r\n");
      out.write("  color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 800px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("  border: 1px solid black;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("  background-color: #f2f2f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td.weekend {\r\n");
      out.write("  color: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td.weekend:first-child {\r\n");
      out.write("  color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td.today {\r\n");
      out.write("  background-color: #4CAF50;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td.other-month {\r\n");
      out.write("  color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("@media screen and (max-width: 768px) {\r\n");
      out.write("  table#calendar {\r\n");
      out.write("    width: 100%; /* Adjust the width as needed for smaller screens */\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("  $(\"#addPlan\").click(function(){\r\n");
      out.write("    var url = \"/planWrite.do\";\r\n");
      out.write("    window.open(url,\"popup\",\"width=600,height=450\");\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function openMoreLink(planyear, planmonth, planday, planList) {\r\n");
      out.write("    return function(event) {\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("        const titlesForDate = [];\r\n");
      out.write("        const planunqList = [];\r\n");
      out.write("\r\n");
      out.write("        for (const item of planList) {\r\n");
      out.write("            if (\r\n");
      out.write("                planyear === item.planyear &&\r\n");
      out.write("                planmonth === item.planmonth - 1 &&\r\n");
      out.write("                planday >= item.planday &&\r\n");
      out.write("                planday <= item.planeday\r\n");
      out.write("            ) {\r\n");
      out.write("                titlesForDate.push(item.plantitle);\r\n");
      out.write("                planunqList.push(item.planunq);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        const titlesJson = JSON.stringify(titlesForDate);\r\n");
      out.write("        const planunqJson = JSON.stringify(planunqList);\r\n");
      out.write("        const url = \"/planDayList.do?titles=\" + encodeURIComponent(titlesJson) + \"&planunqs=\" + encodeURIComponent(planunqJson);\r\n");
      out.write("\r\n");
      out.write("        // Get the click coordinates relative to the document\r\n");
      out.write("        const clickX = event.clientX;\r\n");
      out.write("        const clickY = event.clientY;\r\n");
      out.write("\r\n");
      out.write("        // Open the popup window at the clicked coordinates\r\n");
      out.write("        const popupWidth = 400;\r\n");
      out.write("        const popupHeight = 300;\r\n");
      out.write("        const xOffset = clickX - popupWidth / 2;\r\n");
      out.write("        const yOffset = clickY - popupHeight / 2;\r\n");
      out.write("        const popupOptions = \"width=\" + popupWidth + \",height=\" + popupHeight + \",left=\" + xOffset + \",top=\" + yOffset;\r\n");
      out.write("        window.open(url, \"popupWindow\", popupOptions);\r\n");
      out.write("    };\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	  const calendarBody = document.querySelector(\"#calendar tbody\");\r\n");
      out.write("	  const beforeMonthBtn = document.querySelector(\"#beforeMonth\");\r\n");
      out.write("	  const nextMonthBtn = document.querySelector(\"#nextMonth\");\r\n");
      out.write("	  const monthYearDisplay = document.querySelector(\"#monthYearDisplay\");\r\n");
      out.write("\r\n");
      out.write("	  \r\n");
      out.write("	  const currentDate = new Date();\r\n");
      out.write("	  const currentYear = currentDate.getFullYear();\r\n");
      out.write("	  const currentMonth = currentDate.getMonth() + 1; // JavaScript의 월은 0부터 시작하므로 1을 더해줍니다.\r\n");
      out.write("	  \r\n");
      out.write("	  // resultList 변수를 JavaScript 배열로 초기화\r\n");
      out.write("	  const planList = [\r\n");
      out.write("	    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	  ];\r\n");
      out.write("	  \r\n");
      out.write("	  function generateCalendar(planyear, planmonth) {\r\n");
      out.write("		    const firstDay = new Date(planyear, planmonth, 1);\r\n");
      out.write("		    const lastDay = new Date(planyear, planmonth + 1, 0);\r\n");
      out.write("		    const today = new Date();\r\n");
      out.write("\r\n");
      out.write("		    calendarBody.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("		    let planday = 1;\r\n");
      out.write("		    const startDate = new Date(planyear, planmonth, 1); // Create a Date object for the start date\r\n");
      out.write("		    const endDate = new Date(planyear, planmonth + 1, 0); // Create a Date object for the end date\r\n");
      out.write("\r\n");
      out.write("		    for (let i = 0; i < 6; i++) {\r\n");
      out.write("		      const row = document.createElement(\"tr\");\r\n");
      out.write("		      for (let j = 0; j < 7; j++) {\r\n");
      out.write("		        const cell = document.createElement(\"td\");\r\n");
      out.write("\r\n");
      out.write("		        if ((i === 0 && j < startDate.getDay()) || planday > endDate.getDate()) {\r\n");
      out.write("		          cell.textContent = \"\";\r\n");
      out.write("		          cell.classList.add(\"other-month\");\r\n");
      out.write("		        } else {\r\n");
      out.write("		          cell.textContent = planday;\r\n");
      out.write("		          if (\r\n");
      out.write("		            today.getFullYear() === planyear &&\r\n");
      out.write("		            today.getMonth() === planmonth &&\r\n");
      out.write("		            today.getDate() === planday\r\n");
      out.write("		          ) {\r\n");
      out.write("		            cell.classList.add(\"today\");\r\n");
      out.write("		          }\r\n");
      out.write("		          if (j === 0 || j === 6) {\r\n");
      out.write("		            cell.classList.add(\"weekend\");\r\n");
      out.write("		          }\r\n");
      out.write("\r\n");
      out.write("		          cell.style.position = \"relative\";\r\n");
      out.write("		          cell.style.textAlign = \"left\";\r\n");
      out.write("		          cell.style.verticalAlign = \"top\";\r\n");
      out.write("\r\n");
      out.write("		          const container = document.createElement(\"div\");\r\n");
      out.write("		          let titleCount = 0;\r\n");
      out.write("\r\n");
      out.write("		          for (const item of planList) {\r\n");
      out.write("		            if (\r\n");
      out.write("		              planyear === item.planyear &&\r\n");
      out.write("		              planmonth === item.planmonth - 1 &&\r\n");
      out.write("		              planday >= item.planday && // Check if planday is within the range\r\n");
      out.write("		              planday <= item.planeday\r\n");
      out.write("		            ) {\r\n");
      out.write("		              if (titleCount < 2) { // Only show up to 3 titles\r\n");
      out.write("		                const link = document.createElement(\"a\");\r\n");
      out.write("		                link.href = \"/planDetail.do?planunq=\" + item.planunq;\r\n");
      out.write("		                link.style.color = \"blue\";\r\n");
      out.write("		                link.textContent = item.plantitle;\r\n");
      out.write("		                link.style.fontSize = \"12px\";\r\n");
      out.write("		                link.style.textDecoration = \"none\";\r\n");
      out.write("\r\n");
      out.write("		                container.appendChild(link);\r\n");
      out.write("		                titleCount++;\r\n");
      out.write("		              } else {\r\n");
      out.write("		            	  if (titleCount === 2) {\r\n");
      out.write("		            		  const moreLink = document.createElement(\"a\");\r\n");
      out.write("		            		  moreLink.href = \"#\"; // Replace with your actual URL\r\n");
      out.write("		            		  moreLink.style.color = \"blue\";\r\n");
      out.write("		            		  moreLink.style.fontSize = \"12px\";\r\n");
      out.write("		            		  moreLink.style.textDecoration = \"none\";\r\n");
      out.write("\r\n");
      out.write("		            		  const br = document.createElement(\"br\"); // Add a line break before the \"more+\" link\r\n");
      out.write("		            		  container.appendChild(br);\r\n");
      out.write("		            		  \r\n");
      out.write("		            		  moreLink.textContent = \"more+\";\r\n");
      out.write("		            		  container.appendChild(moreLink);\r\n");
      out.write("\r\n");
      out.write("		            		  const openLinkFunction = openMoreLink(planyear, planmonth, planday, planList);\r\n");
      out.write("		            		  moreLink.addEventListener(\"click\", openLinkFunction);\r\n");
      out.write("\r\n");
      out.write("		            		  break; // Break the loop after showing \"more+\"\r\n");
      out.write("		            		}\r\n");
      out.write("\r\n");
      out.write("		              }\r\n");
      out.write("		              if (item.planeday > planday) {\r\n");
      out.write("		                const br = document.createElement(\"br\");\r\n");
      out.write("		                container.appendChild(br);\r\n");
      out.write("		              } else if (item.planday !== item.planeday) {\r\n");
      out.write("		                const br = document.createElement(\"br\");\r\n");
      out.write("		                container.appendChild(br);\r\n");
      out.write("		              }\r\n");
      out.write("		            }\r\n");
      out.write("		          }\r\n");
      out.write("\r\n");
      out.write("		          cell.appendChild(container);\r\n");
      out.write("\r\n");
      out.write("		          planday++;\r\n");
      out.write("		          cell.style.width = \"100px\";\r\n");
      out.write("		          cell.style.height = \"100px\";\r\n");
      out.write("		          cell.style.boxSizing = \"border-box\";\r\n");
      out.write("		        }\r\n");
      out.write("\r\n");
      out.write("		        row.appendChild(cell);\r\n");
      out.write("		      }\r\n");
      out.write("		      calendarBody.appendChild(row);\r\n");
      out.write("		      if (planday > endDate.getDate()) {\r\n");
      out.write("		        break;\r\n");
      out.write("		      }\r\n");
      out.write("		    }\r\n");
      out.write("\r\n");
      out.write("		    monthYearDisplay.textContent = planyear + \"년 \" + (planmonth + 1) + \"월\";\r\n");
      out.write("	  }\r\n");
      out.write("	  function updateCalendar() {\r\n");
      out.write("	    generateCalendar(currentDate.getFullYear(), currentDate.getMonth());\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	  beforeMonthBtn.addEventListener(\"click\", function() {\r\n");
      out.write("	    currentDate.setMonth(currentDate.getMonth() - 1);\r\n");
      out.write("	    updateCalendar();\r\n");
      out.write("	  });\r\n");
      out.write("\r\n");
      out.write("	  nextMonthBtn.addEventListener(\"click\", function() {\r\n");
      out.write("	    currentDate.setMonth(currentDate.getMonth() + 1);\r\n");
      out.write("	    updateCalendar();\r\n");
      out.write("	  });\r\n");
      out.write("\r\n");
      out.write("	  updateCalendar();\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--header 시작-->\r\n");
      out.write("		<header>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function fn_logout() {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			data : \"\",\r\n");
      out.write("			url  : \"/logout.do\",\r\n");
      out.write("			\r\n");
      out.write("			datatype : \"text\",\r\n");
      out.write("			success  : function(data){\r\n");
      out.write("	            if(data == \"1\" ) {\r\n");
      out.write("	               alert(\"로그아웃되었습니다.\");\r\n");
      out.write("	               location=\"/\";\r\n");
      out.write("	            } else {\r\n");
      out.write("	            	alert(\"로그아웃 실패.\");\r\n");
      out.write("	            } \r\n");
      out.write("	         },\r\n");
      out.write("	         error : function(){\r\n");
      out.write("	            alert(\"전송실패\");\r\n");
      out.write("	         }			\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function fn_bsnmlogout() {\r\n");
      out.write("	      \r\n");
      out.write("	      $.ajax({\r\n");
      out.write("	         type : \"POST\",\r\n");
      out.write("	         data : \"\",\r\n");
      out.write("	         url  : \"/bsnmLogout.do\",\r\n");
      out.write("	         \r\n");
      out.write("	         datatype : \"text\",\r\n");
      out.write("	         success  : function(data){\r\n");
      out.write("               if(data == \"1\" ) {\r\n");
      out.write("                  alert(\"로그아웃되었습니다.\");\r\n");
      out.write("                  location=\"/\";\r\n");
      out.write("               } else {\r\n");
      out.write("                  alert(\"로그아웃 실패.\");\r\n");
      out.write("               } \r\n");
      out.write("            },\r\n");
      out.write("            error : function(){\r\n");
      out.write("               alert(\"전송실패\");\r\n");
      out.write("            }         \r\n");
      out.write("	      });\r\n");
      out.write("	   }\r\n");
      out.write("	\r\n");
      out.write("function fn_adminlogout() {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			data : \"\",\r\n");
      out.write("			url  : \"/adminLogout.do\",\r\n");
      out.write("			\r\n");
      out.write("			datatype : \"text\",\r\n");
      out.write("			success  : function(data){\r\n");
      out.write("	            if(data == \"1\" ) {\r\n");
      out.write("	               alert(\"로그아웃되었습니다.\");\r\n");
      out.write("	               location=\"/\";\r\n");
      out.write("	            } else {\r\n");
      out.write("	            	alert(\"로그아웃 실패.\");\r\n");
      out.write("	            } \r\n");
      out.write("	         },\r\n");
      out.write("	         error : function(){\r\n");
      out.write("	            alert(\"전송실패\");\r\n");
      out.write("	         }			\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<ul class=\"header_left\">\r\n");
      out.write("  <li class=\"header_item\">\r\n");
      out.write("  		<a href=\"/\">\r\n");
      out.write("			<img src=\"/tripImage/hitriplogo.png\">\r\n");
      out.write("		</a>\r\n");
      out.write("	</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<ul class=\"header_right\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <li class=\"header_item\">\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"header_item\">\r\n");
      out.write("    <a class=\"header_link\" href=\"/noticeList.do\">공지사항</a>\r\n");
      out.write("  </li>\r\n");
      out.write("  \r\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</ul>");
      out.write("\r\n");
      out.write("		</header>\r\n");
      out.write("		<!--header 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--nav 시작-->\r\n");
      out.write("		<nav>\r\n");
      out.write("	    	<div class=\"navigation\">\r\n");
      out.write("	      		");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<div class=\"nav_wrap\">\r\n");
      out.write("		<ul class=\"navbar\">\r\n");
      out.write("		  <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/\">Home </a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		  <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"prtBoardList.do\">동행</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		  <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/planMain.do\">일정</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		 <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/tripList.do\">국내여행지</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		 <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/babList.do\">국내맛집</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		 <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/reviewList.do\">여행후기</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		 <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/packBoardList.do\">패키지여행</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		 <li class=\"nav_item\">\r\n");
      out.write("		   <a class=\"nav_link\" href=\"/packReviewList.do\">패키지여행후기</a>\r\n");
      out.write("		  </li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>");
      out.write("\r\n");
      out.write("	    	</div>\r\n");
      out.write("	  	</nav>\r\n");
      out.write("		<!--nav 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--section 시작-->\r\n");
      out.write("    <section>\r\n");
      out.write("      <div class=\"section-wrapper\">\r\n");
      out.write("        <div id=\"calendar-container\" data-resultList=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${planList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("          <div class=\"button-container\">\r\n");
      out.write("			  <div class=\"button-group\">\r\n");
      out.write("			    <button id=\"beforeMonth\">이전 달</button>\r\n");
      out.write("			    <span id=\"monthYearDisplay\"></span>\r\n");
      out.write("			    <button id=\"nextMonth\">다음 달</button>\r\n");
      out.write("			  </div>\r\n");
      out.write("			  <button type=\"button\" id=\"addPlan\">일정추가</button>\r\n");
      out.write("			</div>\r\n");
      out.write("          <table id=\"calendar\">\r\n");
      out.write("            <thead>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <th>일</th>\r\n");
      out.write("                <th>월</th>\r\n");
      out.write("                <th>화</th>\r\n");
      out.write("                <th>수</th>\r\n");
      out.write("                <th>목</th>\r\n");
      out.write("                <th>금</th>\r\n");
      out.write("                <th class=\"weekend\">토</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--section 끝-->\r\n");
      out.write("\r\n");
      out.write("    <!--footer 시작-->\r\n");
      out.write("    <footer>\r\n");
      out.write("      <div class=\"footer\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<div class=\"footer1\">\r\n");
      out.write("   <ul>\r\n");
      out.write("      <li><a class=\"footer_link\" href=\"/service.do\">이용약관</a></li>\r\n");
      out.write("      <li><a class=\"footer_link\" href=\"/policy.do\">개인정보 처리방침</a></li>\r\n");
      out.write("      <li>메일문의 guri@himedia.co.kr</li>         \r\n");
      out.write("   </ul>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!--footer 끝-->\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /planboard/planMain.jsp(203,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /planboard/planMain.jsp(203,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/planboard/planMain.jsp(203,5) '${planList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${planList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /planboard/planMain.jsp(203,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	      { planunq 	: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.planunq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(",\r\n");
            out.write("	    	planyear 	: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.planyear}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(",\r\n");
            out.write("	    	planmonth 	: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.planmonth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(",\r\n");
            out.write("	    	planday 	: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.planday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(",\r\n");
            out.write("	    	planeyear 	: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.planeyear}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(",\r\n");
            out.write("	    	planemonth 	: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.planemonth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(",\r\n");
            out.write("	    	planeday 	: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.planeday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(",\r\n");
            out.write("	    	plantitle 	: \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.plantitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("	    	plancontent : \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.plancontent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("	    	planopen 	: \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.planopen}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\r\n");
            out.write("	    	userid		: \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("	        \r\n");
            out.write("	      },\r\n");
            out.write("	    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /planboard/../include/header.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("s_userid");
      // /planboard/../include/header.jsp(10,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/planboard/../include/header.jsp(10,0) '${sessionScope.SessionUserID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionUserID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /planboard/../include/header.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("s_bsnmid");
      // /planboard/../include/header.jsp(11,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/planboard/../include/header.jsp(11,0) '${sessionScope.SessionBsnmID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionBsnmID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /planboard/../include/header.jsp(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("s_adminid");
      // /planboard/../include/header.jsp(12,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/planboard/../include/header.jsp(12,0) '${sessionScope.SessionAdminID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionAdminID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /planboard/../include/header.jsp(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("s_superid");
      // /planboard/../include/header.jsp(13,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/planboard/../include/header.jsp(13,0) '${sessionScope.SessionAdminSuperID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionAdminSuperID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /planboard/../include/header.jsp(89,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_adminid != null or s_superid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"../adminNoticeList.do\">관리자페이지</a>\r\n");
          out.write("  </li>\r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /planboard/../include/header.jsp(96,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /planboard/../include/header.jsp(97,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_bsnmid !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('사');
          out.write('업');
          out.write('자');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_bsnmid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /planboard/../include/header.jsp(98,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_adminid !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('관');
          out.write('리');
          out.write('자');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_adminid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /planboard/../include/header.jsp(99,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_superid !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("최고관리자");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_superid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /planboard/../include/header.jsp(105,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == null and s_bsnmid == null and\r\n  				s_adminid == null and s_superid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"../joinWrite.do\">회원가입</a>\r\n");
          out.write("  </li>\r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"/loginWrite.do\">로그인</a>\r\n");
          out.write("  </li> \r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /planboard/../include/header.jsp(115,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"../mbrModify.do\">정보수정</a>\r\n");
          out.write("  </li>\r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"javascript:fn_logout()\">로그아웃</a>\r\n");
          out.write("  </li>  \r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /planboard/../include/header.jsp(125,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_bsnmid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"../bsnmModify.do\">정보수정</a>\r\n");
          out.write("  </li>\r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"javascript:fn_bsnmlogout()\">로그아웃</a>\r\n");
          out.write("  </li>  \r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent(null);
      // /planboard/../include/header.jsp(134,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_adminid != null or s_superid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <li class=\"header_item\">\r\n");
          out.write("    <a class=\"header_link\" href=\"javascript:fn_adminlogout()\">로그아웃</a>\r\n");
          out.write("  </li>  \r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }
}
